spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${DB_NAME_LOCAL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

cache:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/homewatts_cache
    username: ${CACHE_DATASOURCE_USERNAME:${DB_USERNAME}}
    password: ${CACHE_DATASOURCE_PASSWORD:${DB_PASSWORD}}

logging:
  level:
    com.pvmanagement: DEBUG

jwt:
  refresh-token-cookie-secure: false