spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/${DB_NAME_LOCAL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

logging:
  level:
    com.pvmanagement: DEBUG

jwt:
  refresh-token-cookie-secure: false